/**
* play-with-friends
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.theodm.pwf.routing.model

import de.theodm.Connectivity


/**
* 
* Values: DISCONNECTED,ACTIVE,INACTIVE
*/
enum class RsConnectivity(val value: kotlin.String) {

    DISCONNECTED("Disconnected"),

    ACTIVE("Active"),

    INACTIVE("Inactive");

    fun toConnectivity(): Connectivity {
        return Connectivity.valueOf(this.value);
    }

}

