/**
* play-with-friends
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.theodm.pwf.routing.model

import java.time.Instant

/**
 * 
 * @param creationTime 
 * @param lobbyID 
 * @param host 
 * @param participants 
 * @param participantsConnectivityInfo 
 * @param inGame
 * @param settings 
 */
data class RsLobby(
    val creationTime: Instant,
    val lobbyID: String,
    val host: RsParticipant,
    val participants: List<RsParticipant>,
    val participantsConnectivityInfo: Map<String, RsConnectivity>,
    val inGame: Boolean,
    val settings: RsLobbySettings
) 

