/**
* play-with-friends
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.theodm.pwf.routing.model

import de.theodm.pwf.user.User

data class RsUser(
    val userName: String,
    val userPublicID: kotlin.String,
    val userKey: kotlin.String
)

fun User.toRsUser(): RsUser {
    return RsUser(
        this.userName.toString(),
        this.userPublicID,
        this.userKey
    )
}

